version: '3'
services:
  # Servicio de Node.js
  node_app:
    build: .
    image: jperezfrias33/backend-app:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/app/dist
    networks:
      - my_network
    environment:
      - PORT=${PORT}
      - MONGODB_CNN=${MONGODB_CNN}
      - SECRETPRIVATEKEY=${SECRETPRIVATEKEY}
    restart: always

networks:
  my_network:
